main: ca.spottedleaf.oldgenerator.OldGenerator
version: ${version}
name: OldGenerator
load: STARTUP
api-version: "1.21"
authors: [Spottedleaf]
description: Provides historical Beta 1.7.3 and Minecraft 1.2.5 world generation for modern servers.
folia-supported: true
