main: ca.spottedleaf.oldgenerator.OldGenerator
version: ${version}
name: OldGenerator
load: STARTUP
api-version: "1.21"
authors: [Spottedleaf]
description: A standalone Minecraft 1.2.5 world generator for modern Paper servers.
folia-supported: true
